version: '2.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.178.28
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  solr:
    image: solr:8.5
    ports:
      - "8983:8983"
    entrypoint:
      - bash
      - "-c"
      - "precreate-core resources; exec solr -f"
  twitter-crawler:
    build: ./services/twitter-crawler
    depends_on: 
      - kafka
    environment:
      KAFKA_BROKER: 192.168.178.28:9092
  mention-matcher:
    build: ./services/mention-matcher
    depends_on: 
      - kafka
    environment:
      KAFKA_BROKER: 192.168.178.28:9092